### ISSUE TITLE
百度版权信息不显示

### ISSUE THREAD

**Issue by thomasyu929** [huiyan-fe/react-bmapgl#58]
请问为什么只会显示百度logo但不显示版权信息
如何生成百度的版权信息呢？

**Comment by zzdoreen** [comment]
```css
.BMap_cpyCtrl {
  display: block
}
```
